all: kr1

kr1: kr1v1n1 kr1v2n1 kr1v3n1 kr1v4n1

kr1v1n1: kr1_v1_n1.c
	gcc -ggdb -o kr1v1n1 kr1_v1_n1.c

kr1v2n1: kr1_v2_n1.c
	gcc -ggdb -o kr1v2n1 kr1_v2_n1.c

kr1v3n1: kr1_v3_n1.c
	gcc -ggdb -o kr1v3n1 kr1_v3_n1.c

kr1v4n1: kr1_v4_n1.c
	gcc -ggdb -o kr1v4n1 kr1_v4_n1.c
clean:
	rm -f kr1v1n1 kr1v2n1 kr1v3n1 kr1v4n1
